{
 "title": "Spring Boot 2  Statistics (test)",
 "description": "Dashboard for Spring Boot2.1 Statistics(based on Spring Boot2 Statistic by micrometer-prometheus).",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(prometheus_from)" } },
   {
    "name": "namespace",
    "label": "NameSpace",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{prometheus_from=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{prometheus_from=~\"$cluster\", namespace=\"$namespace\"} , app)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{prometheus_from=~\"$cluster\", namespace=\"$namespace\",app=~\"$app\"} , pod)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{prometheus_from=~\"$cluster\", namespace=\"$namespace\",app=~\"$app\"} , pool)"
    }
   },
   {
    "name": "cache",
    "label": "Cache",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{prometheus_from=~\"$cluster\", namespace=\"$namespace\", app=~\"$app\", pod=\"$pod\" }, cache)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_uptime_seconds{app=~\"$app\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=~\"$app\", pod=~\"$pod\", area=~\"heap\"})*100/sum(jvm_memory_max_bytes{app=~\"$app\",pod=~\"$pod\", area=~\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=~\"$app\", pod=~\"$pod\", area=~\"nonheap\"})*100/sum(jvm_memory_max_bytes{app=~\"$app\",pod=~\"$pod\", area=~\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{app=~\"$app\", pod=~\"$pod\"}",
     "legendFormat": "Open Files {{instance}}"
    },
    {
     "expr": "process_files_max_files{app=~\"$app\", pod=~\"$pod\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_start_time_seconds{app=~\"$app\", pod=~\"$pod\"}*1000)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{pod=~\"$pod\", app=~\"$app\"}",
     "legendFormat": "System CPU Usage {{instance}}"
    },
    {
     "expr": "process_cpu_usage{pod=~\"$pod\", app=~\"$app\"}",
     "legendFormat": "Process CPU Usage {{instance}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{pod=~\"$pod\", app=~\"$app\"}",
     "legendFormat": "Load Average [1m] {{instance}}"
    },
    {
     "expr": "system_cpu_count{pod=~\"$pod\", app=~\"$app\"}",
     "legendFormat": "CPU Core Size {{instance}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "timeseries",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 16 },
     "targets": [
      { "expr": "logback_events_total", "legendFormat": "{{level}}" }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "cache Gets",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cache_gets_total{pod=~\"$pod\", app=~\"$app\", result=\"hit\", cache=~\"$cache\" }[1m])",
       "legendFormat": "{{cache}} HIT"
      },
      {
       "expr": "rate(cache_gets_total{pod=~\"$pod\",app=~\"$app\", result=\"miss\", cache=~\"$cache\" }[1m])",
       "legendFormat": "{{cache}} MISS"
      }
     ]
    },
    {
     "title": "cache evictions",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cache_evictions_total{app=~\"$app\",pod=~\"$pod\",cache=~\"$cache\"}[1m])",
       "legendFormat": "{{cache}}"
      }
     ]
    },
    {
     "title": "cache Removals",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cache_removals{ pod=~\"$pod\", app=~\"$app\", cache=~\"$cache\"}[1m])",
       "legendFormat": "{{cache}}"
      }
     ]
    },
    {
     "title": "cache Puts",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cache_puts_total{pod=~\"$pod\", app=~\"$app\", cache=~\"$cache\"}[1m])",
       "legendFormat": "{{cache}}"
      }
     ]
    },
    {
     "title": "Cache MISS (%)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cache_percentage{app=~\"$app\", pod=~\"$pod\", result=\"miss\" , cache=~\"$cache\" }",
       "legendFormat": "{{cache}} MISS"
      }
     ]
    },
    {
     "title": "cache_average_put_time_microseconds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cache_average_put_time_microseconds{pod=~\"$pod\", app=~\"$app\", cache=~\"$cache\"}",
       "legendFormat": "{{cache}}"
      }
     ]
    },
    {
     "title": "cache_average_get_time_microseconds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cache_average_get_time_microseconds{pod=~\"$pod\",app=~\"$app\", cache=~\"$cache\"}",
       "legendFormat": "{{cache}}"
      }
     ]
    }
   ]
  },
  { "title": "JVM Statistics - GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GC Count (sec)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{pod=~\"$pod\", app=~\"$app\"}[1m])",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{pod=~\"$pod\", app=~\"$app\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  { "title": "JVM Statistics - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=~\"$pod\", app=~\"$app\"}",
     "legendFormat": "{{id}} used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pod=~\"$pod\", app=~\"$app\"}",
     "legendFormat": "{{id}} committed"
    },
    {
     "expr": "jvm_memory_max_bytes{pod=~\"$pod\", app=~\"$app\"}",
     "legendFormat": "{{id}} max"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_classes_total{pod=~\"$pod\", app=~\"$app\"}[5m])",
     "legendFormat": "Classes Unloaded"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{pod=~\"$pod\", app=~\"$app\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{pod=~\"$pod\", app=~\"$app\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{pod=~\"$pod\", app=~\"$app\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{pod=~\"$pod\", app=~\"$app\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{pod=~\"$pod\", app=~\"$app\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{pod=~\"$pod\", app=~\"$app\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{pod=~\"$pod\", app=~\"$app\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{pod=~\"$pod\", app=~\"$app\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{pod=~\"$pod\", app=~\"$app\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{pod=~\"$pod\", app=~\"$app\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "jvm_threads_states_threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{pod=~\"$pod\", app=~\"$app\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "HikariCP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections{pod=~\"$pod\", app=~\"$app\"})"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_active{pod=~\"$pod\", app=~\"$app\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_idle{pod=~\"$pod\", app=~\"$app\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{pod=~\"$pod\", app=~\"$app\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Connection Timeout Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_timeout_total{pod=~\"$pod\", app=~\"$app\"})"
      }
     ]
    },
    {
     "title": "Connection Creation Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_creation_seconds_sum{pod=~\"$pod\", app=~\"$app\"} / hikaricp_connections_creation_seconds_count{pod=~\"$pod\", app=~\"$app\"}",
       "legendFormat": "Creation Time {{pool}}"
      }
     ]
    },
    {
     "title": "Connection Usage Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_usage_seconds_sum{pod=~\"$pod\", app=~\"$app\"} / hikaricp_connections_usage_seconds_count{pod=~\"$pod\", app=~\"$app\"}",
       "legendFormat": "Usage Time"
      }
     ]
    },
    {
     "title": "Connection Acquire Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_acquire_seconds_sum{pod=~\"$pod\", app=~\"$app\"} / hikaricp_connections_acquire_seconds_count{pod=~\"$pod\", app=~\"$app\"}",
       "legendFormat": "Acquire Time"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{pod=~\"$pod\", app=\"$app\", uri!~\".*actuator.*\"}[1m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Request Count (stacking)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{pod=~\"$pod\", app=~\"$app\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{pod=~\"$pod\", app=~\"$app\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{pod=~\"$pod\", app=~\"$app\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  { "title": "Spring Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "spring_kafka_listener_seconds_max Kafka Listener Timer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_kafka_listener_seconds_max{namespace=\"$namespace\",app=~\"$app\", pod=~\"$pod\"}",
     "legendFormat": "{{name}} {{result}} {{exception}}"
    }
   ]
  },
  {
   "title": "spring_kafka_listener_seconds Kafka Listener Timer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spring_kafka_listener_seconds_count{namespace=\"$namespace\",app=~\"$app\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{name}} {{result}} {{exception}}"
    }
   ]
  },
  { "title": "Logback Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "INFO logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{pod=~\"$pod\", app=~\"$app\", level=\"info\"}[5m])",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{pod=~\"$pod\", app=~\"$app\", level=\"error\"}[5m])",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{pod=~\"$pod\", app=~\"$app\", level=\"warn\"}[5m])",
     "legendFormat": "warn",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 104 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{pod=~\"$pod\", app=~\"$app\", level=\"debug\"}[5m])",
     "legendFormat": "debug",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "TRACE logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 104 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{pod=~\"$pod\", app=~\"$app\", level=\"trace\"}[5m])",
     "legendFormat": "trace",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "collapsed": true
  }
 ]
}